spring.datasource.url=jdbc:postgresql://localhost:5432/ayudaz_db
spring.datasource.username=postgres
spring.datasource.password=pgadmin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

<<<<<<< Updated upstream
server.port=8080
=======


spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.auto-commit=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.jpa.open-in-view=false
firebase.config.path=${FIREBASE_CONFIG_PATH}
>>>>>>> Stashed changes

spring.web.cors.allowed-origins=http://localhost:3000